version: '2'

services:
    motion:
        image: motion:test #This is my local imgae, replace with most recent travis pre-release
        network_mode: "host"
        command: "motion --cid=48 --cidSM=219 --constantSpeed=1 --speedRequest=2 --verbose=1 --id=1"

    steering:
        image: steering:test #This is my local imgae, replace with most recent travis pre-release
        network_mode: "host"
        command: "steering --cid=48 --cidSteering=219"

    # cfsd18-sim-visualization:
    #     image: chalmersfsd/cfsd18-sim-visualization:pre-release-778bfb6
    #     network_mode: "host"
    #     command: "--cid=250"
